version: "3"

services:
    app:
        build: .
        volumes:
            - ./:/usr/src/app
        ports:
            - 32321:8000
        depends_on:
            - db

    db:
        image: postgres:12-bullseye
        environment:
            POSTGRES_USER: table_builder
            POSTGRES_PASSWORD: table_builder
            POSTGRES_DB: table_builder
            PGDATA: /data/postgres
        expose:
            - 5432
        volumes:
            - dbData:/data/postgres

volumes:
    dbData:
